# Generated by Django 5.0 on 2024-03-26 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bill',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0, help_text='AZN'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='AZN', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_account',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
