# Generated by Django 5.0.2 on 2024-02-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=1000)),
                ('weight', models.PositiveIntegerField(default=0, help_text='in grams')),
                ('price', models.PositiveSmallIntegerField(default=0, help_text='AZN')),
                ('baked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
