# Generated by Django 5.0.2 on 2024-02-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.FloatField(default=0, help_text='AZN'),
        ),
    ]
