# Generated by Django 5.0 on 2024-03-26 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_cake_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='stars',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
