# Generated by Django 5.0 on 2024-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_alter_cake_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
    ]
